## CSC 217: Week One Homework

#### This homework is due at **6:00 PM on Wednesday, September 4th**. Any submissions made after that time will receive no credit.

Please email me this completed notebook (File -> Download as Notebook) at <eagovino@ccny.cuny.edu>

#### 1. TIRC Survey

Please go to [this link](https://tinyurl.com/y4oh83sh) (open in a new window!!) to fill out an anonymous survey for TIRC. Please print your name below to confirm that you have done this.

In [ ]:
print('Nahin Imtiaz')

#### 2. Survey for Me

This is an informal survey so that I can get more of a grasp of your preferences, abilities and interests. Please go to [this link](https://docs.google.com/forms/d/e/1FAIpQLScyEc-30-qkJ0gbV5EJ6xbAXmg5_Uh4JHbg-Ch2zUd8FQkosw/viewform?usp=pp_url) (open in a new window!!) to fill out a survey so I can learn more about you. No wrong answers! (Also sorry - some of these questions are repetitive from the above survey but I don't receive that one). Please print your name below to confirm that you have done this.

In [ ]:
print('Nahin Imtiaz')

**3. Anaconda Download**

Anaconda is an easy way to download Python and all of the packages we'll use in this class - and much more - onto your machine. It is compatible with all major operating systems. While working with Python on your machine as opposed to Binder isn't required for the course, it's heavily encouraged due to the limitations of Binder, particularly its nasty habit of timing out after a pretty short period of time of inactivity. 

Please download Anaconda from [here](https://www.anaconda.com/download/) (open in a new window!!) and print your name below to confirm that you have downloaded and installed it successfully. Depending on your operating system, you might have to do some Googling to get it to install properly, but it shouldn't be hard. If you can't successfully install it for any reason, please explain why below - otherwise, please print your name.

In [ ]:
print('I have installed anaconda but when i tried to open anaconda navigator app,its not opening.')

**4. Git Download**

We will be using Github in class as a means of downloading updated coursework. Please follow the instructions [here](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) (open in a new window!!) to download Git on your machine. If you can't successfully install it for any reason, please explain why below - otherwise, please print your name.

In [ ]:
print('Nahin Imtiaz')

**5. Python Introduction Tutorial**

The tutorial [here](https://www.learnpython.org/) (open in a new window!!) will introduce you to some of the core concepts of Python. Please complete the "Learn the Basics" and "Data Science Tutorials" sections and confirm that you have completed them by printing your name below.

**Please note that the attached tutorial can take up to 2-3 hours to complete. Act accordingly so that your Binder instance doesn't timeout - save and download this file if you need to, and then you can upload it back to the instance later.**

In [ ]:
print('Nahin Imtiaz')

**6. Wikipedia Pages**

Today, we successfully scraped the Wikipedia page telling us the number one songs of 2019 with one line of code. Knowing how powerful and easy this - what are at least three Wikipedia pages that you find interesting that you could potentially work with in class? Create a cell below this one and share! (make down the cell is in 'Markdown' mode)

In [2]:
import random
import scipy.stats as stats
import statsmodels.api as sm
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
print('List of largest companies by revenue')
df = pd.read_html('https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue', header=0)[0]
df

List of largest companies by revenue

,Rank,Name,Industry,Revenue(USD millions),Profit(USD millions),Employees,Country,Ref
0,1,Walmart,Retail,"$514,405","$6,670",2200000,United States,[5]
1,2,Sinopec,Oil and gas,"$414,649","$5,845",619151,China,[6]
2,3,Royal Dutch Shell,Oil and gas,"$396,556","$23,352",81000,Netherlands / United Kingdom,[7]
3,4,China National Petroleum,Oil and gas,"$569,696","$2,270",1382401,China,[8]
4,5,State Grid,Electricity,"$387,056","$8,174",917717,China,[9]
5,6,Saudi Aramco,Oil and gas,"$355,905","$110,974",76418,Saudi Arabia,[10]
6,7,BP,Oil and gas,"$303,738","$9,383",73000,United Kingdom,[11]
7,8,ExxonMobil,Oil and gas,"$290,212","$20,840",71000,United States,[12]
8,9,Volkswagen,Automotive,"$278,341","$14,332",664496,Germany,[13]
9,10,Toyota,Automotive,"$272,612","$16,982",370870,Japan,[14]
10,11,Apple,Electronics,"$265,595","$59,531",132000,United States,[15]
11,12,Berkshire Hathaway,Conglomerate,"$247,837","$4,021",389000,United States,[16]
12,13,Amazon,Retail,"$232,887","$10,073",647000,United States,[17]
13,14,UnitedHealth,Healthcare,"$226,247","$11,986",300000,United States,[18]
14,15,Samsung Electronics,Electronics,"$221,579","$39,895",221579,South Korea,[19]
15,16,Glencore,Commodities,"$219,754","$3,408",85504,Switzerland,[20]
16,17,McKesson,Healthcare,"$214,319",$34,70000,United States,[21]
17,18,Daimler,Automotive,"$197,515","$8,555",298683,Germany,[22]
18,19,CVS Health,Healthcare,"$194,579",-$594,295000,United States,[23]
19,20,Total,Oil and gas,"$184,106","$11,446",104460,France,[24]
20,21,China State Construction,Construction,"$181,524","$3,159",302827,China,[25]
21,22,Trafigura,Commodities,"$180,744",$849,4316,Singapore,[26]
22,23,Foxconn,Electronics,"$175,617","$4,281",667680,Taiwan,[27]
23,24,Exor,Financials,"$175,009","$1,589",314790,Italy,[28]
24,25,AT&T,Telecommunications,"$170,756","$19,370",254000,United States,[29]
25,26,ICBC,Financials,"$168,979","$45,002",449296,China,[30]
26,27,AmerisourceBergen,Pharmaceuticals,"$167,939","$1,658",20500,United States,[31]
27,28,Chevron,Oil and gas,"$166,339","$14,824",48600,United States,[32]
28,29,Ping An Insurance,Financials,"$163,597","$16,237",342550,China,[33]
29,30,Ford,Automotive,"$160,338","$3,677",199000,United States,[34]
30,31,China Construction Bank,Financials,"$151,110","$38,498",366996,China,[35]
31,32,General Motors,Automotive,"$147,049","$8,014",173000,United States,[36]
32,33,Mitsubishi,Conglomerate,"$145,243","$5,328",79994,Japan,[37]
33,34,Honda,Automotive,"$143,302","$5,504",219772,Japan,[38]
34,35,Costco,Retail,"$141,576","$3,134",194000,United States,[39]
35,36,Agricultural Bank of China,Financials,"$139,523","$30,656",477526,China,[40]
36,37,Alphabet,Internet,"$136,819","$30,736",98771,United States,[41]
37,38,Cardinal Health,Pharmaceuticals,"$136,809",$256,50200,United States,[42]
38,39,SAIC Motor,Automotive,"$136,392","$5,443",147738,China,[43]
39,40,Walgreens Boots Alliance,Retail,"$131,537","$5,024",299000,United States,[44]
40,41,JPMorgan Chase,Financials,"$131,412","$32,474",256105,United States,[45]
41,42,Gazprom,Oil and gas,"$131,302","$23,199",466100,Russia,[46]
42,43,Verizon,Telecommunications,"$130,863","$15,528",144500,United States,[47]
43,44,Bank of China,Financials,"$127,714","$27,255",310119,China,[48]
44,45,Allianz,Financials,"$126,779","$8,806",142460,Germany,[49]
45,46,AXA,Financials,"$125,578","$2,525",104065,France,[50]
46,47,Kroger,Retail,"$121,162","$3,110",453000,United States,[51]
47,48,General Electric,Conglomerate,"$120,268","-$22,355",283000,United States,[52]
48,49,Fannie Mae,Financials,"$120,101","$15,959",7400,United States,[53]
49,50,Lukoil,Oil and gas,"$119,145","$9,863",102500,Russia,[54]

In [3]:
print('List of most suscribed youtube channels')
df = pd.read_html('https://en.wikipedia.org/wiki/List_of_most-subscribed_YouTube_channels', header=0)[0]
df

List of most suscribed youtube channels

,Rank,Chg.,Channel,Subscribers[2](millions),Network[B],Primarylanguage(s),Contentcategory[2]
0,1,NaN,T-Series[7],110,T-Series[8],Hindi[9][10],Music
1,2,NaN,PewDiePie[11],100,N/A[12][13],English[14],Entertainment
2,3,NaN,5-Minute Crafts[15],60,Channel Frederator[16],English[14],How-to
3,4,NaN,Cocomelon - Nursery Rhymes[17],58,Fullscreen[18],English[14],Education
4,5,NaN,SET India[19],54,SET[20],Hindi[21][22],Entertainment
5,6,NaN,Canal KondZilla[23],51,ONErpm[24],Portuguese[9],Music
6,7,NaN,WWE[25],47,WWE[26],English[27][28][29],Sports
7,8,NaN,Justin Bieber[30],46,N/A[C][31][32],English[27][28][29],Entertainment
8,9,NaN,Dude Perfect[33],45,N/A[C][31][32],English[27][28][29],Sports
9,10,NaN,Zee Music Company[34],42,Zee Music Company[35],Hindi[36][37],Music
10,11,NaN,Badabun[38],42,N/A[D][39][40],Spanish,Entertainment
11,12,NaN,Ed Sheeran[41],41,N/A[D][39][40],English[42],Music
12,13,NaN,HolaSoyGerman.[43],39,HolaSoyGerman[44],Spanish[9],Entertainment
13,14,NaN,EminemMusic[45],38,UniversalMC[E][46],English,Music
14,15,NaN,Marshmello[47],38,Monstercat Media[48],English,Music
15,16,NaN,Ariana Grande[49],37,N/A[F][50],English,Music
16,17,NaN,whinderssonnunes[51],36,Fullscreen[52],Portuguese,Comedy
17,18,NaN,JuegaGerman[53],36,HolaSoyGerman[54],Spanish,Games
18,19,NaN,elrubiusOMG[55],35,Mixicom[56],Spanish,Comedy
19,20,NaN,Taylor Swift[57],35,N/A[G][58][H][59],English,Music
20,21,NaN,Katy Perry[60],34,N/A[G][58][H][59],English,Entertainment
21,22,NaN,Zee TV[61],34,DMCL[62],Hindi[63][64],Entertainment
22,23,NaN,Felipe Neto[65],34,Maker Studios[66],Portuguese,Entertainment
23,24,NaN,TheEllenShow[67],33,WarnerMedia[I][68],English,Entertainment
24,25,NaN,✿ Kids Diana Show[69],33,AIR[70],English,Entertainment
25,26,NaN,Fernanfloo[71],33,BroadbandTV[72],Spanish,Games
26,27,NaN,Rihanna[73],32,N/A[J][74][K][75],English,Entertainment
27,28,NaN,Like Nastya Vlog[76],32,N/A[J][74][K][75],Russian,People
28,29,NaN,One Direction[77],29,N/A[J][74][K][75],English,Music
29,30,NaN,Blackpink[78],29,YG Entertainment[79],Korean,People
30,31,NaN,Bright Side[80],29,NaN,English,How-to
31,32,NaN,Alan Walker[81],29,RouteNote[82],English,Music
32,33,NaN,Movieclips[83],29,Movieclips[84],English,Film
33,34,NaN,ibighit[85],28,LOEN Entertainment[L][86],Korean,Music
34,35,NaN,Get Movies[87],28,LetsonCorp[88],Russian,Entertainment
35,36,NaN,YouTube[89],28,Google[90],English,News
36,37,NaN,Wave Music[91],27,HT Mobile[92],Bhojpuri,Music
37,38,NaN,Vegetta777[93],27,Mixicom[94],Spanish,Games
38,39,NaN,Trap Nation[95],27,N/A[M][96],English,Music
39,40,NaN,Shemaroo Filmi Gaane[97],27,Shemaroo Music[98],Hindi,Music
40,41,NaN,Sony Music India[99],27,Sony BMG[100],Hindi,Music
41,42,NaN,Você Sabia?[101],27,Maker Studios[102],Portuguese,Entertainment
42,43,NaN,Goldmines Telefilms[103],27,Goldmines[104],Hindi[105],Film
43,44,NaN,Maroon 5[106],26,N/A[N][107],English,Music
44,45,NaN,Luccas Neto - Luccas Toon[108],26,BroadbandTV[109],Portuguese,People
45,46,NaN,Shakira[110],26,N/A[O][111],Spanish and English,People
46,47,NaN,Luis Fonsi[112],26,N/A[O][111],Spanish,Entertainment
47,48,NaN,Luisito Comunica[113],26,MiTú[114],Spanish,Comedy
48,49,NaN,ChuChu TV Nursery Rhymes & Kids Songs[115],26,ChuChu TV Studios[116],English,Education
49,50,NaN,Spinnin' Records[117],25,Spinnin' Records[118],English,Music
50,"As of August 31, 2019 UTC","As of August 31, 2019 UTC","As of August 31, 2019 UTC","As of August 31, 2019 UTC","As of August 31, 2019 UTC","As of August 31, 2019 UTC","As of August 31, 2019 UTC"

In [4]:
print('BBCs 100 Greatest Films of the 21st Century')
df = pd.read_html('https://en.wikipedia.org/wiki/BBC%27s_100_Greatest_Films_of_the_21st_Century', header=0)[0]
df

BBCs 100 Greatest Films of the 21st Century

,No.,Title,Director,Country,Year
0,1,Mulholland Drive,David Lynch,NaN,2001
1,2,In the Mood for Love,Wong Kar-wai,NaN,2000
2,3,There Will Be Blood,Paul Thomas Anderson,NaN,2007
3,4,Spirited Away,Hayao Miyazaki,NaN,2001
4,5,Boyhood,Richard Linklater,NaN,2014
5,6,Eternal Sunshine of the Spotless Mind,Michel Gondry,NaN,2004
6,7,The Tree of Life,Terrence Malick,NaN,2011
7,8,Yi Yi,Edward Yang,NaN,2000
8,9,A Separation,Asghar Farhadi,NaN,2011
9,10,No Country for Old Men,Joel Coen and Ethan Coen,NaN,2007
10,11,Inside Llewyn Davis,Joel Coen and Ethan Coen,NaN,2013
11,12,Zodiac,David Fincher,NaN,2007
12,13,Children of Men,Alfonso Cuarón,NaN,2006
13,14,The Act of Killing,Joshua Oppenheimer,NaN,2012
14,15,"4 Months, 3 Weeks and 2 Days",Cristian Mungiu,NaN,2007
15,16,Holy Motors,Leos Carax,NaN,2012
16,17,Pan's Labyrinth,Guillermo del Toro,NaN,2006
17,18,The White Ribbon,Michael Haneke,NaN,2009
18,19,Mad Max: Fury Road,George Miller,NaN,2015
19,20,"Synecdoche, New York",Charlie Kaufman,NaN,2008
20,21,The Grand Budapest Hotel,Wes Anderson,NaN,2014
21,22,Lost in Translation,Sofia Coppola,NaN,2003
22,23,Caché,Michael Haneke,NaN,2005
23,24,The Master,Paul Thomas Anderson,NaN,2012
24,25,Memento,Christopher Nolan,NaN,2001
25,26,25th Hour,Spike Lee,NaN,2002
26,27,The Social Network,David Fincher,NaN,2010
27,28,Talk to Her,Pedro Almodóvar,NaN,2002
28,29,WALL-E,Andrew Stanton,NaN,2008
29,30,Oldboy,Park Chan-wook,NaN,2003
...,...,...,...,...,...
72,73,Before Sunset,Richard Linklater,NaN,2004
73,74,Spring Breakers,Harmony Korine,NaN,2012
74,75,Inherent Vice,Paul Thomas Anderson,NaN,2014
75,76,Dogville,Lars von Trier,NaN,2003
76,77,The Diving Bell and the Butterfly,Julian Schnabel,NaN,2007
77,78,The Wolf of Wall Street,Martin Scorsese,NaN,2013
78,79,Almost Famous,Cameron Crowe,NaN,2000
79,80,The Return,Andrey Zvyagintsev,NaN,2003
80,81,Shame,Steve McQueen,NaN,2011
81,82,A Serious Man,Joel Coen and Ethan Coen,NaN,2009
82,83,A.I. Artificial Intelligence,Steven Spielberg,NaN,2001
83,84,Her,Spike Jonze,NaN,2013
84,85,A Prophet,Jacques Audiard,NaN,2009
85,86,Far from Heaven,Todd Haynes,NaN,2002
86,87,Amélie,Jean-Pierre Jeunet,NaN,2001
87,88,Spotlight,Tom McCarthy,NaN,2015
88,89,The Headless Woman,Lucrecia Martel,NaN,2008
89,90,The Pianist,Roman Polanski,NaN,2002
90,91,The Secret in Their Eyes,Juan José Campanella,NaN,2009
91,92,The Assassination of Jesse James by the Coward...,Andrew Dominik,NaN,2007
92,93,Ratatouille,Brad Bird,NaN,2007
93,94,Let the Right One In,Tomas Alfredson,NaN,2008
94,95,Moonrise Kingdom,Wes Anderson,NaN,2012
95,96,Finding Nemo,Andrew Stanton,NaN,2003
96,97,White Material,Claire Denis,NaN,2009
97,98,Ten,Abbas Kiarostami,NaN,2002
98,99,The Gleaners and I,Agnès Varda,NaN,2000
99,100,Carlos,Olivier Assayas,NaN,2010
100,100,Requiem for a Dream,Darren Aronofsky,NaN,2000
101,100,Toni Erdmann,Maren Ade,NaN,2016

**7. Next Week's Readings**

Please complete the readings listed in the README section of this week's class.